// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfuX_NduIUH91FmUsixh30lkuewvbHtfM',
    appId: '1:289118886387:web:3bb6bcc5412b4419c39a86',
    messagingSenderId: '289118886387',
    projectId: 'shopping-cart-app-6c1dc',
    authDomain: 'shopping-cart-app-6c1dc.firebaseapp.com',
    storageBucket: 'shopping-cart-app-6c1dc.appspot.com',
    measurementId: 'G-MX79YNGXGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtAo4HVAmGcIwUGNGhSPrwFZLLrOjAIJY',
    appId: '1:289118886387:android:026afe27498cd3bfc39a86',
    messagingSenderId: '289118886387',
    projectId: 'shopping-cart-app-6c1dc',
    storageBucket: 'shopping-cart-app-6c1dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMPaPnSO8U9xYVglQwOsZZkixQOXeKPSE',
    appId: '1:289118886387:ios:a0c72ea48809a5e5c39a86',
    messagingSenderId: '289118886387',
    projectId: 'shopping-cart-app-6c1dc',
    storageBucket: 'shopping-cart-app-6c1dc.appspot.com',
    iosBundleId: 'com.example.shoppingCartApp',
  );
}
